In [1]:
import numpy as np 

A = np.arange(1, 17).reshape(4, 4)
print(A)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [2]:
print(A[ 1:3 , 2:4 ])

[[ 7  8]
 [11 12]]


In [3]:
A[:,-1] = -1
print(A)

[[ 1  2  3 -1]
 [ 5  6  7 -1]
 [ 9 10 11 -1]
 [13 14 15 -1]]


In [4]:
vecteur = np.arange(20)
print(vecteur)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [5]:
pairs = vecteur[::2]
print("Éléments pairs:", pairs)

Éléments pairs: [ 0  2  4  6  8 10 12 14 16 18]


In [6]:
impairs = vecteur[1::2]
print("Éléments impairs:", impairs)

Éléments impairs: [ 1  3  5  7  9 11 13 15 17 19]


In [7]:
elements_pas_3 = vecteur[5::3]
print("Éléments à partir de l'indice 5 avec un pas de 3:", elements_pas_3)

Éléments à partir de l'indice 5 avec un pas de 3: [ 5  8 11 14 17]
